### ISSUE TITLE
Please ask before taking code

### ISSUE THREAD

**Issue by khalwat** [dutchheight/aws-serverless-image-handler#1]
![Screen Shot 2019-08-06 at 2 35 04 PM](https://user-images.githubusercontent.com/7570798/62567076-73be6080-b858-11e9-9f63-5707cde5ff94.png)

Would appreciate you asking before lifting code. I would have been fine with it.

Yours: https://github.com/dutchheight/aws-serverless-image-handler/blob/master/src/services/HelperService.php#L32

Mine: https://github.com/nystudio107/craft-imageoptimize-sharp/blob/v1/src/imagetransforms/SharpImageTransform.php#L150

From the article [Setting Up Your Own Image Transform Service](https://nystudio107.com/blog/setting-up-your-own-image-transform-service)

**Comment by KevinBeckers** [comment]
I needed a solution for aws without image optimize. Sorry, wont happen again. I will figure out another way to translate the focalpoint and update the code.

**Comment by khalwat** [comment]
You're free to use the code... just would appreciate asking first is all!

We're good! Keep it in there.

**Comment by KevinBeckers** [comment]
You are right, didn't stood still by the fact that using your code is wrong. I changed the code in the latest commit and mentioned your excellent blog post in case people like more info about the subject.
