### ISSUE TITLE
Consider removing default height/width

### ISSUE THREAD

**Issue by andrewmenich** [dutchheight/aws-serverless-image-handler#5]
Removing the default height/width would allow for users to enter only one dimension and receive an image with a preserved aspect ratio resized to the specified height or width (so long as they have not selected `fill` for the resize mode.)

Alternatively, it might be nice to have some plugin options allowing users to enter a default height/width.

**Comment by KevinBeckers** [comment]
This would be a good feature. I will likely implement this.

**Comment by KevinBeckers** [comment]
I removed the default height and width in fb1049066256d257cc6a0efa2f7ea43fe4be1ee3. So you are able to set these in the template.
