### ISSUE TITLE
Couldn't install plugin

### ISSUE THREAD

**Issue by umkasanki** [dutchheight/aws-serverless-image-handler#6]
I'm trying to install your plugin but I get cp error 'Couldn't install plugin' :(

**Comment by KevinBeckers** [comment]
Which craft version do you use? Can u provide some extra info?

**Comment by umkasanki** [comment]
Craft Solo 3.3.1.2
Amazon S3 1.2.5
AWS Image Handler 1.1.1

My logs in the attachment.
Thanks
[logs.zip](https://github.com/dutchheight/aws-serverless-image-handler/files/3594184/logs.zip)

**Comment by KevinBeckers** [comment]
Can you check if you have the database table `fieldgroups`? It looks like you are missing a Craft table.

**Comment by umkasanki** [comment]
My DB, fieldgroups table not missed
[db.sql.zip](https://github.com/dutchheight/aws-serverless-image-handler/files/3594325/db.sql.zip)

**Comment by KevinBeckers** [comment]
Thanks, I found the problem. Fixed in 3e2f1f355eb50283ae5e8a9096106b9f67fa1fb9. I will release an update soon.
